/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyIdRouteImport } from './routes/journey/$id'
import { Route as JourneyIdIndexRouteImport } from './routes/journey/$id/index'
import { Route as JourneyIdPhase2RouteImport } from './routes/journey/$id/phase2'
import { Route as JourneyIdPhase1RouteImport } from './routes/journey/$id/phase1'
import { Route as JourneyIdCompareRouteImport } from './routes/journey/$id/compare'
import { Route as JourneyIdPhase3NewRouteImport } from './routes/journey/$id/phase3.new'
import { Route as JourneyIdPhase3EntryIdRouteImport } from './routes/journey/$id/phase3.$entryId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIdRoute = JourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIdIndexRoute = JourneyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdPhase2Route = JourneyIdPhase2RouteImport.update({
  id: '/phase2',
  path: '/phase2',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdPhase1Route = JourneyIdPhase1RouteImport.update({
  id: '/phase1',
  path: '/phase1',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdCompareRoute = JourneyIdCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdPhase3NewRoute = JourneyIdPhase3NewRouteImport.update({
  id: '/phase3/new',
  path: '/phase3/new',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdPhase3EntryIdRoute = JourneyIdPhase3EntryIdRouteImport.update({
  id: '/phase3/$entryId',
  path: '/phase3/$entryId',
  getParentRoute: () => JourneyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/journey/$id': typeof JourneyIdRouteWithChildren
  '/journey/$id/compare': typeof JourneyIdCompareRoute
  '/journey/$id/phase1': typeof JourneyIdPhase1Route
  '/journey/$id/phase2': typeof JourneyIdPhase2Route
  '/journey/$id/': typeof JourneyIdIndexRoute
  '/journey/$id/phase3/$entryId': typeof JourneyIdPhase3EntryIdRoute
  '/journey/$id/phase3/new': typeof JourneyIdPhase3NewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/journey/$id/compare': typeof JourneyIdCompareRoute
  '/journey/$id/phase1': typeof JourneyIdPhase1Route
  '/journey/$id/phase2': typeof JourneyIdPhase2Route
  '/journey/$id': typeof JourneyIdIndexRoute
  '/journey/$id/phase3/$entryId': typeof JourneyIdPhase3EntryIdRoute
  '/journey/$id/phase3/new': typeof JourneyIdPhase3NewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/journey/$id': typeof JourneyIdRouteWithChildren
  '/journey/$id/compare': typeof JourneyIdCompareRoute
  '/journey/$id/phase1': typeof JourneyIdPhase1Route
  '/journey/$id/phase2': typeof JourneyIdPhase2Route
  '/journey/$id/': typeof JourneyIdIndexRoute
  '/journey/$id/phase3/$entryId': typeof JourneyIdPhase3EntryIdRoute
  '/journey/$id/phase3/new': typeof JourneyIdPhase3NewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/journey/$id'
    | '/journey/$id/compare'
    | '/journey/$id/phase1'
    | '/journey/$id/phase2'
    | '/journey/$id/'
    | '/journey/$id/phase3/$entryId'
    | '/journey/$id/phase3/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/journey/$id/compare'
    | '/journey/$id/phase1'
    | '/journey/$id/phase2'
    | '/journey/$id'
    | '/journey/$id/phase3/$entryId'
    | '/journey/$id/phase3/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/journey/$id'
    | '/journey/$id/compare'
    | '/journey/$id/phase1'
    | '/journey/$id/phase2'
    | '/journey/$id/'
    | '/journey/$id/phase3/$entryId'
    | '/journey/$id/phase3/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  JourneyIdRoute: typeof JourneyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$id': {
      id: '/journey/$id'
      path: '/journey/$id'
      fullPath: '/journey/$id'
      preLoaderRoute: typeof JourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$id/': {
      id: '/journey/$id/'
      path: '/'
      fullPath: '/journey/$id/'
      preLoaderRoute: typeof JourneyIdIndexRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/phase2': {
      id: '/journey/$id/phase2'
      path: '/phase2'
      fullPath: '/journey/$id/phase2'
      preLoaderRoute: typeof JourneyIdPhase2RouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/phase1': {
      id: '/journey/$id/phase1'
      path: '/phase1'
      fullPath: '/journey/$id/phase1'
      preLoaderRoute: typeof JourneyIdPhase1RouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/compare': {
      id: '/journey/$id/compare'
      path: '/compare'
      fullPath: '/journey/$id/compare'
      preLoaderRoute: typeof JourneyIdCompareRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/phase3/new': {
      id: '/journey/$id/phase3/new'
      path: '/phase3/new'
      fullPath: '/journey/$id/phase3/new'
      preLoaderRoute: typeof JourneyIdPhase3NewRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/phase3/$entryId': {
      id: '/journey/$id/phase3/$entryId'
      path: '/phase3/$entryId'
      fullPath: '/journey/$id/phase3/$entryId'
      preLoaderRoute: typeof JourneyIdPhase3EntryIdRouteImport
      parentRoute: typeof JourneyIdRoute
    }
  }
}

interface JourneyIdRouteChildren {
  JourneyIdCompareRoute: typeof JourneyIdCompareRoute
  JourneyIdPhase1Route: typeof JourneyIdPhase1Route
  JourneyIdPhase2Route: typeof JourneyIdPhase2Route
  JourneyIdIndexRoute: typeof JourneyIdIndexRoute
  JourneyIdPhase3EntryIdRoute: typeof JourneyIdPhase3EntryIdRoute
  JourneyIdPhase3NewRoute: typeof JourneyIdPhase3NewRoute
}

const JourneyIdRouteChildren: JourneyIdRouteChildren = {
  JourneyIdCompareRoute: JourneyIdCompareRoute,
  JourneyIdPhase1Route: JourneyIdPhase1Route,
  JourneyIdPhase2Route: JourneyIdPhase2Route,
  JourneyIdIndexRoute: JourneyIdIndexRoute,
  JourneyIdPhase3EntryIdRoute: JourneyIdPhase3EntryIdRoute,
  JourneyIdPhase3NewRoute: JourneyIdPhase3NewRoute,
}

const JourneyIdRouteWithChildren = JourneyIdRoute._addFileChildren(
  JourneyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  JourneyIdRoute: JourneyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
